name = "hello-bulma"
description = "My Personal Website Hugo theme built from hello-friend theme"
features = ["blog", "shortcode", "syntax Highlighting"]
homepage = "https://github.com/sinicide/hugo-theme-hello-bulma/"
min_version = 0.90
tags = [
  "blog",
  "clean",
  "dark",
  "highlighting",
  "minimal",
  "monochromatic",
  "multilingual",
  "personal",
  "responsive",
  "simple",
  "technical",
]

[author]
homepage = "https://github.com/sinicide"
name = "sinicide"

[original]
name = "panr"
homepage = "https://radoslawkoziel.pl"
repo = "https://github.com/panr/hugo-theme-hello-friend"